# Generated by Django 3.0.7 on 2020-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201108_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ph_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
