# Generated by Django 3.0.7 on 2020-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_auto_20201107_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='wage',
        ),
        migrations.AddField(
            model_name='job',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='living_space',
            field=models.BooleanField(default=False),
        ),
    ]
