# Generated by Django 3.0.7 on 2020-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_auto_20201108_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='wage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.AddField(
            model_name='job',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='living_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('1', 'Plumbing'), ('2', 'Carpentry'), ('3', 'Masonary'), ('4', 'Electrical Repair')], max_length=20),
        ),
    ]
